lib/Selenium/Remote/Driver.pm
lib/Selenium/Remote/Mock/RemoteConnection.pm
lib/Test/Selenium/Remote/Driver.pm
lib/Test/Selenium/Remote/Role/DoesTesting.pm
t/Test-Selenium-Remote-Driver.t

I raise this issue mainly because I found myself writing a lot lately : 
```perl 
$driver->default_finder('id');
$driver->find_element_ok('some_id', 'my element was found'); 
$driver->default_finder('xpath'); 
$driver->find_element_ok('//some_xpath', 'my other element was found');
```
If we could pass the locator strategy as an argument, it would allow one to write  : 
```perl 
$driver->find_element_ok('some_id','id','my element was found'); 
$driver->find_element_ok('//some_xpath','xpath', 'my other element was found'); 
```
There might be some issues doing this, but overall it would improve the readability of code written with T::S::R::D.

'find_element'-like functions in Test::Selenium::Remote::Driver should support a locator strategy as an argument

---

lib/Test/Selenium/Remote/Driver.pm
lib/Test/Selenium/Remote/Role/DoesTesting.pm
t/Test-Selenium-Remote-Driver.t

Basically because there is a coercion on the `default_finder` attribute, which makes the attribute already translated when the default finder was changed. 
The problem is not apparent when your default finder is xpath, but gets visible for something else. 
A solution could be to translate back the finder in T::S::R::D when we use the default finder, so that find_element gets the correct parameter.

Passing finders to some T::S::R::D functions won't work if the default finder has been changed beforehand

---

lib/Selenium/Remote/Driver.pm

Hi folks,
Executing a command on a stale element gives an error but does not show which command failed (see the error below). These type of warnings also do not show a stack trace and it is also not clear which command caused the error.
It would be helpful if the attempted command could be shown in the error as well, to help find which line caused the issue.
To duplicate the below error:
1. Open a page
2. Find an element on the page and store in a variable
3. Refresh the page
4. Attempt to click on the found element
**Patch**
I have created the following patch with this improvement:
```
diff --git a/lib/Selenium/Remote/Driver.pm b/lib/Selenium/Remote/Driver.pm
index e339ad6..69bbe51 100644
--- a/lib/Selenium/Remote/Driver.pm
+++ b/lib/Selenium/Remote/Driver.pm
@@ -497,6 +497,8 @@ sub …
```

Command info when element is stale

---

lib/Selenium/CanStartBinary.pm
lib/Selenium/Chrome.pm
lib/Selenium/Firefox.pm
lib/Selenium/PhantomJS.pm
lib/Selenium/Remote/Driver.pm

binary startup fixes

---

lib/Selenium/Remote/Driver.pm

Moose version 2.1210
Selenium::Remote::Driver version 0.2101
```perl
package Extended::Driver;
use Moose;
extends 'Selenium::Remote::Driver';
1;
```
Result:
<pre>
Deep recursion on subroutine "Moo::HandleMoose::FakeMetaClass::isa" at /home/michael/perl5/perlbrew/perls/perl-5.14.2/lib/site_perl/5.14.2/Devel/StackTrace.pm line 80.
Deep recursion on subroutine "Moo::HandleMoose::inject_real_metaclass_for" at /home/michael/perl5/perlbrew/perls/perl-5.14.2/lib/site_perl/5.14.2/Moo/HandleMoose/FakeMetaClass.pm line 17.
<pre>

Extending with Moose causes Deep recursion in Moo::HandleMoose

---

cpanfile
t/03-spec-coverage.t

https://github.com/gempesaw/Selenium-Remote-Driver/blob/59090690a1fed7a29214b29ccad8c7a69125980e/t/03-spec-coverage.t#L11-L13
no need for an extra dep, and LWP::Simple isn't used anywhere else.

replace LWP::Simple with LWP::UserAgent

---

lib/Selenium/Remote/Driver.pm

Guys,
When my Selenium test scripts fail I see the following message:
```
Error while executing command: clickElement: An element command could not be completed because the element is not visible on the page.: Element is not currently visible and so may not be interacted with
Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
System info: host: 'TechWires-MacBook-Pro-15.local', ip: '192.168.22.35', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.7.5', java.version: '1.8.0_25'
Driver info: driver.version: unknown at (eval 58) line 17.
(in cleanup) Can't call method "get_params" on an undefined value at C:/Strawberry/perl/site/lib/Selenium/Remote/Driver.pm line 269 during global destruction.
```
I'm pretty sure the "get_params" method was OK before I …

(in cleanup) Can't call method "get_params" on an undefined value

---

lib/Test/Selenium/Remote/Driver.pm
t/Test-Selenium-Remote-Driver.t

The fix should work, but there are two points to take care of : 
* ~~add in the documentation of T::S::R::D that when using `error_handler`, the responsibility of failing the test is on the handler for `find_` family functions, as, because of our implementation of S::R::D, the code won't die anymore when making a call to `find_element` with something that does not exist~~
* ~~write more tests !!~~
All good now, @gempesaw can you review it to see if anything is missing ?

[WIP] Fix 209

---

lib/Test/Selenium/Remote/Driver.pm
lib/Test/Selenium/Remote/Role/DoesTesting.pm
t/Test-Selenium-Remote-Driver.t

`find_no_element_ok` had a nasty bug where, when an element was actually found by `find_element`, the test was not failing. This is now fixed (added a test to check that too). 
On top of that, I made the documentation modifications asked in #211. 
@gempesaw please have a look :+1:

Fix find no elt ok

---

cpanfile
t/Waiter.t

From an email:
> All my work laptops are Windows based computers, so I am stuck with Activestate or Strawberry perl. I tried to install Selenium::Remote:Driver with both cpanm and ppm commands, and both fails due to Time::Mock issue.  Seems like Time::Mock does not support Windows: http://code.activestate.com/ppm/Time-Mock/
> I tried force install commands on cpan, but that didn't work either.  I am not a professional programmer (I am actually a Pharmacist), so I am pretty much stuck right now. Should I try to downgrade a Selenium version and try to manually install?
I'll try to figure out how to either remove it or not make it required for installation, I guess.

Make time mock not required for installation

---

lib/Selenium/Remote/Driver.pm
t/01-driver.t

'Error while executing command: setImplicitWaitTimeout: An unknown server-side error occurred
while processing the command.: java.lang.String cannot be cast to java.lang.Number at /opt/perl
/5.22/lib/site_perl/5.22.0/Selenium/Remote/Driver.pm line 300.
The problem shows up when dealing with test plans stored in YAML and read via YAML::XS, something in Load is treating the timeout numeric as string-y (maybe leaving the SV with both numeric and string set to true?) which freaks out Java. Due to the perl debugger thinking the value is numeric, I'm guessing that the issue is with bindings rather than YAML::XS.
Short version of the fix is adding zero on the way into *timeout* subs, for example:
sub set_implicit_wait_timeout
{
my ( $self, $ms ) = @_;
my $res    = { 'command' => …

milliseconds value passed to java needs to be numeric.

---

README.md
driver-example.pl
lib/Selenium/Remote/Mock/RemoteConnection.pm
t/00-load.t
t/01-driver.t
t/02-webelement.t
t/03-spec-coverage.t
t/04-commands-implemented.t
t/10-switch-to-window.t
t/11-action-chains.t
t/CanStartBinary.t
t/Finders.t
t/Firefox-Profile.t
t/Remote-Connection.t
t/Test-Selenium-Remote-Driver-google.t
t/Test-Selenium-Remote-Driver.t
t/Test-Selenium-Remote-WebElement.t
t/Waiter.t
t/bin/record.pl
t/convenience.t
t/error.t
t/pod.t

POD, README, few executables that need it all have "#!/bin/env perl", test files all begin with a blank line.

Replace "#!.*perl" with "#!/bin/env perl" where necessary, remove elsewhere

---

lib/Selenium/Remote/Driver.pm
t/01-driver-pac.t

In Selenium/Remote/Driver.pm, only "http" URL is allowed for proxyAutoConfigURL.
We need this to work for file URLs also (e.g., file://c/bin/test.pac)

proxyAutoconfigUrl should support local file URLs also

---

lib/Test/Selenium/Remote/Driver.pm
t/Test-Selenium-Remote-Driver.t

Something like the following:
```my $driver = Test::Selenium::Remote::Driver->new;
$driver->content_like(qr/I am not found/);```
causes an error unless `error_handler` is set.
Pull request coming shortly: the new tests, I think, make it pretty clear.

content_like dies on mismatch without error_handler

---

README.md
lib/Selenium/CanStartBinary.pm
lib/Selenium/CanStartBinary/FindBinary.pm
lib/Selenium/Chrome.pm
lib/Selenium/Firefox.pm
lib/Selenium/Firefox/Binary.pm
lib/Selenium/Firefox/Profile.pm
lib/Selenium/InternetExplorer.pm
lib/Selenium/PhantomJS.pm
lib/Selenium/Remote/Driver.pm
t/CanStartBinary.t

FF 48 will no longer support the .xpi addon version for FF startup, in favor of Marionette & geckodriver.. FF 47 currently has a startup bug that prevents it from working with Se 2.53.0. There's a [fix in the works](https://github.com/seleniumhq/selenium/issues/2110#issuecomment-224413609), but by the time 48 rolls around, we'll need to be supporting Marionette anyway.

add compatibility with marionette (geckodriver) for firefox 48

---

lib/Selenium/Firefox.pm
lib/Selenium/Remote/Commands.pm
lib/Selenium/Remote/Driver.pm
t/04-commands-implemented.t

geckodriver (Firefox>48) supports the jsonwire extension for context switching: `/session/{sessionId}/moz/context`
Available contexts: chrome and content. _Chrome_ is a privileged scope where you can access things like the Firefox UI itself. _Content_ scope is where things like webpages live.
A few notes/questions:
1. Should the command extension be moved in another module? I added them in `Selenium/Remote/Commands.pm` to demo the change.
2. I guess that we don't want our `@CARP_NOT;` in `Selenium/Firefox.pm`?
3. No tests added yet .If this looks ok overall, I'll add.

Add command for Firefox context switching

---

lib/Selenium/Remote/Driver.pm

It was not obvious to get `Selenium::Remote::Driver` running with Firefox 47 or lower (like 45 ESR) together with Selenium 3, so I wanted to share the documentation for this.
Maybe it would be worth adding a more obvious way in the Selenium::Remote::Driver API to toggle the marionette flag. The unusual `\0` syntax is currently needed because it represents a JSON false value.
At the moment Marionette seems to have serious bugs which prevent older test codebases to run with current Firefoxes, but they plan to fix these issues soon so that old test codebases should run unmodified also with Selenium 3 and recent Firefoxes.

Added documentation on how to run Firefox 47 or earlier on Selenium 3+.

---

lib/Selenium/Remote/Driver.pm

Sorry, this slipped in from a setup script where I needed to escape the `\`. What we really need is a reference to 0 (`\0`) as a JSON false representation.

Fix typo: send \0 as a JSON false value, not \\0.

---

dist.ini

https://github.com/RsrchBoy/Dist-Zilla-Plugin-ContributorsFromGit/issues/19 is a longstanding issue.

[ContributorsFromGit] -> [Git::Contributors]

---

lib/Selenium/Remote/Commands.pm
lib/Selenium/Remote/Driver.pm

Geckodriver seems to follow very strictly the new W3C API.
* set timeout: [Relevant part of the Specs][1]
* move_to: uses the new actions API, [Relevant part of the Specs][2]
[1]: https://w3c.github.io/webdriver/webdriver-spec.html#set-timeouts
[2]: https://w3c.github.io/webdriver/webdriver-spec.html#pointer-actions

Fix set_timeout and move_to for Selenium::Firefox

---

lib/Selenium/Remote/Driver.pm

This fixes issue #375 until Firefox/Selenium can negociate again

Temporarily fix Firefox platform problem

---

lib/Selenium/Remote/Driver.pm

Pass the arguments used to the user provided error handler, and returns its answer to allow it to fix the error if possible

Add context to error handler. Fixes #378

---

lib/Selenium/Remote/Driver.pm

Remove the geckodriver restriction for the GET /status endpoint.
Version 0.12.0 added status on 2017-01-03
See: https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver/status

Remove get /status restriction on firefox/geckodriver

---

lib/Selenium/Remote/Driver.pm

As we discussed a few weeks back.

Fix #398: set_window_{position,size} validate args and convert to numeric

---

README.md
lib/Selenium/Remote/Driver.pm

The link to refer to JSONWireProtocol is old. Changing that to current one.

bugFix: Change the hyperlink to refer JSONWireProtocol

---

lib/Selenium/CanStartBinary.pm

On MacOS, the `lsof -i :<port>` command seems to show multiple processes
have the port open, one of which is the current Perl program. Since this
one mostly comes first in the output, `shutdown_unix_binary` tries to
kill the `perl` process, not the browser process. Filtering out the
current `perl` process from the process we're trying to kill fixes this
issue.
Before this change, the `t/CanStartBinary.t` test exited with signal 9 and the following output:
```
$ RELEASE_TESTING=1 prove t/CanStartBinary.t
t/CanStartBinary.t .. 1/? Could not kill driver process! you may have to clean up manually. at /Users/doug/perl/Selenium-Remote-Driver/lib/Selenium/CanStartBinary.pm line 431.
t/CanStartBinary.t .. 5/? Could not kill driver process! you may have to clean up manually. at …
```

fix search for unix binary on MacOS

---

lib/Selenium/Remote/Driver.pm
lib/Selenium/Remote/Spec.pm
lib/Selenium/Remote/WebElement.pm
t/01-webdriver3.t

Added W3C WebDriver support for Chrome which provides the ability to use Chrome and chromedriver v75+ in default w3c mode.
https://chromium.googlesource.com/chromium/src/+/master/docs/chromedriver_status.md
https://chromedriver.storage.googleapis.com/75.0.3770.8/notes.txt

Added W3C WebDriver support when using Chrome

---

lib/Selenium/Remote/Driver.pm

Variable name $self->{browser} doesn't exist. Needed to be:
$self->{browser_name} for the croak

Driver.pm screenshot method referenced incorrect

---

lib/Selenium/Remote/Spec.pm

Added 'goog:loggingPrefs', to _caps array.

#449: fix chromedriver performance logging

---

lib/Test/Selenium/Remote/Driver.pm

For https://github.com/RotherOSS/otobo I want to subclass `Test::Selenium::Remote::Driver`. However I encountered a stumbling block. When used the the subclass I ran into errors, stating  `javascript` was not enabled. This was unexpected as `Selenium::Remote::Driver` enables `javascript`per default. 
I gather that the effect comes from the support for `$ENV{TWD_JAVASCRIPT}`. Thus the patch that check whether env vars exist before they are used as a fallback.

Default for 'javascript' when constructing Test::Selenium::Remote::Driver

---

lib/Test/Selenium/Remote/Driver.pm

I noticed some inconsistencies in the POD for Test::Selenium::Remote::Driver. The relevant mixups were "content" vs. "text" and "regex" vs. "string". Here is an attempt to improve the POD.

POD improvements for Test::Selenium::Remote::Driver

---

lib/Test/Selenium/Remote/Role/DoesTesting.pm

I started with trying to improve the generic test description for `find_no_element_ok()`. But then I got carried away with refactoring. 
In case this patch is too much, I can provide a PR that tackles only the generic message.

Issue #535: refactoring and generic test message

---

lib/Selenium/Waiter.pm
t/13-waiter.t

When wait_until elapsed timeout, it's hard to distinguish it from assertion success.
The PR makes debug mode to warn 'timeout' when it is.

make waiter timeout recognizable

---

lib/Selenium/Firefox/Binary.pm

There is no "firefox-bin" any more since Firefox 121.
See also https://github.com/SeleniumHQ/selenium/issues/13350

Check "firefox" too for Firefox binary on Mac
